2019-05-26 11:08:25.952654: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-26 11:08:26.539822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:04:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2019-05-26 11:08:26.539898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2019-05-26 11:08:26.929829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-26 11:08:26.929885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2019-05-26 11:08:26.929894: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2019-05-26 11:08:26.930220: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10413 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
train step loss recon_loss kl_loss
Traceback (most recent call last):
  File "train_vision.py", line 37, in <module>
    dataset.load_new_file_batch(new_epoch=True)
  File "/data/beeperman/Projects/wme/objects/model.py", line 81, in load_new_file_batch
    self.file_batch_dataset = self.create_dataset(self.load_raw_data_list(self.filename_batch_list[self.file_batch_count]), self.shuffle)
  File "/data/beeperman/Projects/wme/objects/model.py", line 114, in load_raw_data_list
    raw_data = np.load(os.path.join(self.data_dir, filename))['obs']
  File "/home/beeperman/.conda/envs/wme/lib/python3.5/site-packages/numpy/lib/npyio.py", line 258, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/beeperman/.conda/envs/wme/lib/python3.5/site-packages/numpy/lib/format.py", line 726, in read_array
    data = _read_bytes(fp, read_size, "array data")
  File "/home/beeperman/.conda/envs/wme/lib/python3.5/site-packages/numpy/lib/format.py", line 865, in _read_bytes
    r = fp.read(size - len(data))
  File "/home/beeperman/.conda/envs/wme/lib/python3.5/zipfile.py", line 844, in read
    data = self._read1(n)
  File "/home/beeperman/.conda/envs/wme/lib/python3.5/zipfile.py", line 920, in _read1
    data = self._decompressor.decompress(data, n)
KeyboardInterrupt
